apiVersion: v1
kind: Service
metadata:
  name: backend-service  
  labels:
    app: backend # חובה כדי שה-ServiceMonitor ימצא אותו
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 5000
    - name: http-metrics # השם שה-ServiceMonitor מחפש
      port: 5001
      targetPort: 5001
  selector:
    app: backend