kind: Service
metadata:
  name: backend-service
  labels:
    app: backend # חובה כדי שה-ServiceMonitor ימצא אותו
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 5000
  selector:
    app: backend