
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels:
    release: prometheus
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: backend # ימצא את ה-Service בזכות ה-labels שהוספנו למעלה
  endpoints:
  - port: http-metrics # ימצא את הפורט הנכון ב-Service
    path: /metrics
    interval: 15s
