apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:        # <--- הוספנו את זה! חשוב שה-Monitor ימצא את השירות
    app: my-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-metrics # <--- עכשיו השם והפורט הם באותו פריט (תחת אותו מקף)
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: my-app