apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels:
    release: prometheus
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: backend # ימצא את ה-Service בזכות ה-labels
  endpoints:
  # ✅ התיקון כאן: שינוי ל-http כדי שייגש ל-targetPort 5000
  - port: http 
    path: /metrics
    interval: 15s