controller:
  serviceType: LoadBalancer # מאפשר גישה דרך localhost
  installPlugins: # תוספים קריטיים שחוסכים זמן הגדרה
    - kubernetes:4203.v152de0381f9b_
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.1
    - docker-workflow:572.v300f295b_316d
    - helm:0.10
  storageClass: hostpath # מתאים ל-Docker Desktop
persistence:
  size: 5Gi