# ---- הקיים שלך ----
backend:
  image:
    repository: "213daniel/flask-app-backend"
    tag: "53"
  service:
    type: ClusterIP
    port: 5000
  resources: {}

frontend:
  image:
    repository: "213daniel/flask-app-frontend"
    tag: "53"
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources: {}

env:
  secretName: "mysql-credentials"

config:
  DB_HOST: "mysql.default.svc.cluster.local"

# ---- תוספת חדשה: autoscaling ----
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 50