backend:
  replicaCount: 1
  image:
    repository: "213daniel/flask-app-backend"
    tag: "76"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  resources: {}
  tag: "75"
frontend:
  image:
    repository: "213daniel/flask-app-frontend"
    tag: "76"
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources: {}
  tag: "75"
env:
  secretName: "mysql-credentials"
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 50
