backend:
  replicaCount: 1
  image:
    repository: "213daniel/flask-app-backend"
    tag: "55"
  service:
    type: ClusterIP
    port: 5000
  resources: {}

frontend:
  image:
    repository: "213daniel/flask-app-frontend"
    tag: "55"
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources: {}

env:
  secretName: "mysql-credentials"

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 50
