backend:
  image:
    repository: "213daniel/flask-app-backend"
    tag: "latest"
  service:
    port: 5000
  resources: {}

frontend:
  image:
    repository: "213daniel/flask-app-frontend"
    tag: "latest"
  service:
    port: 80
  resources: {}

config:
  DB_HOST: "mysql.default.svc.cluster.local"